import type { ScannedElement } from './dom-scanner';

export interface RankedSelector {
  selector: string;
  confidence: SelectorConfidence;
  strategy: SelectorStrategyName;
}

export type SelectorConfidence = 'high' | 'medium' | 'low';

export type SelectorStrategyName =
  | 'testId'
  | 'id'
  | 'ariaLabel'
  | 'name'
  | 'role'
  | 'placeholder'
  | 'href'
  | 'css-text';

const AUTO_ID_PATTERNS: RegExp[] = [
  /^radix-/,
  /^react-select-/,
  /^react-/,
  /^rc-/,
  /^ember\d/,
  /^__next/,
  /^mui-/,
  /^headlessui-/,
  /^chakra-/,
  /^ant-/,
  /^el-/,
  /^\d+$/,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /^:[a-z0-9]+:$/,
  /^u[0-9a-f]{6,}$/i,
  /^j_id\d/,
];

export function isAutoGeneratedId(id: string): boolean {
  return AUTO_ID_PATTERNS.some((p) => p.test(id));
}

function escQuote(s: string): string {
  return s.replace(/"/g, '\\"');
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max);
}

export class SelectorStrategy {
  rank(el: ScannedElement, index: number): RankedSelector {
    if (el.testId) {
      return {
        selector: `[data-testid="${escQuote(el.testId)}"]`,
        confidence: 'high',
        strategy: 'testId',
      };
    }

    if (el.id && !isAutoGeneratedId(el.id)) {
      if (/^[a-zA-Z_][\w-]*$/.test(el.id)) {
        return { selector: `#${el.id}`, confidence: 'high', strategy: 'id' };
      }
      return {
        selector: `[id="${escQuote(el.id)}"]`,
        confidence: 'high',
        strategy: 'id',
      };
    }

    if (el.ariaLabel) {
      return {
        selector: `[aria-label="${escQuote(el.ariaLabel)}"]`,
        confidence: 'high',
        strategy: 'ariaLabel',
      };
    }

    if (el.name) {
      return {
        selector: `[name="${escQuote(el.name)}"]`,
        confidence: 'high',
        strategy: 'name',
      };
    }

    const roleSelector = this.tryRoleSelector(el);
    if (roleSelector) return roleSelector;

    if (el.placeholder) {
      return {
        selector: `[placeholder="${escQuote(el.placeholder)}"]`,
        confidence: 'medium',
        strategy: 'placeholder',
      };
    }

    if (el.tag === 'a' && el.href && !el.href.startsWith('javascript:')) {
      const cleanHref = el.href.split('?')[0].split('#')[0];
      if (cleanHref && cleanHref !== '/' && cleanHref.length < 120) {
        return {
          selector: `a[href="${escQuote(cleanHref)}"]`,
          confidence: 'medium',
          strategy: 'href',
        };
      }
    }

    return this.fallbackSelector(el, index);
  }

  private tryRoleSelector(el: ScannedElement): RankedSelector | null {
    const role = el.ariaRole || this.implicitRole(el);
    if (!role) return null;

    const text = (el.text || '').trim();
    if (!text || text.length > 60) return null;

    const safeText = escQuote(truncate(text, 50));

    return {
      selector: `${el.tag}[role="${role}"]:has-text("${safeText}")`,
      confidence: 'medium',
      strategy: 'role',
    };
  }

  private implicitRole(el: ScannedElement): string | null {
    switch (el.tag) {
      case 'button': return 'button';
      case 'a': return 'link';
      case 'input': {
        if (el.type === 'checkbox') return 'checkbox';
        if (el.type === 'radio') return 'radio';
        if (el.type === 'range') return 'slider';
        if (el.type === 'search') return 'searchbox';
        return 'textbox';
      }
      case 'select': return 'combobox';
      case 'textarea': return 'textbox';
      default: return null;
    }
  }

  private fallbackSelector(el: ScannedElement, index: number): RankedSelector {
    const text = (el.text || '').trim();
    const tag = el.tag;

    if (text && text.length <= 50) {
      const safeText = escQuote(text);
      if (tag === 'button') {
        return {
          selector: `button:has-text("${safeText}")`,
          confidence: 'low',
          strategy: 'css-text',
        };
      }
      if (tag === 'a') {
        return {
          selector: `a:has-text("${safeText}")`,
          confidence: 'low',
          strategy: 'css-text',
        };
      }
    }

    if ((tag === 'input' || tag === 'textarea' || tag === 'select') && el.type) {
      return {
        selector: `${tag}[type="${el.type}"]`,
        confidence: 'low',
        strategy: 'css-text',
      };
    }

    return {
      selector: `xpath=(//${tag})[${index + 1}]`,
      confidence: 'low',
      strategy: 'css-text',
    };
  }
}
