apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jmeter-worker-hpa
  namespace: performance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jmeter-worker
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
